### ISSUE TITLE
Article image upload sometimes doesn't take

### ISSUE THREAD

**Issue by mbertrand** [mitodl/mit-open#139]
## Expected Behavior
Upload an image into the article editor then immediately click the Save button.

## Current Behavior
Sometimes the image doesn't appear and the saved HTML is 
```
"html": "<figure class=\"image\"><img></figure>",
```

Doesn't happen if I wait a bit before clicking Save, my guess is the image hasn't completely uploaded yet to embedly.

## Steps to Reproduce
1. Go to http://localhost:8063/articles/<article_id>
2. Upload a large image
3. Immediately click "Save" after the image appears in the editor

## Possible Solution
Disable "Save" button until image is fully processed?

**Comment by ChristopherChudzicki** [comment]
Yes, this is happening because the image upload is not finished.

Apparently Ckeditor actually has a (very hard to see) progress bar for the image upload and uses the locally defined image as a preview while that's in place.

<img width="393" alt="Screenshot 2023-10-16 at 12 23 00 PM" src="https://github.com/mitodl/mit-open/assets/9010790/0b4dd901-9f29-4d00-a033-d786fe6182ab">

Relevant:
- https://ckeditor.com/docs/ckeditor5/latest/api/module_image_imageupload_imageuploadprogress-ImageUploadProgress.html#event-set:isEnabled

**Comment by ChristopherChudzicki** [comment]
Fixed by #145
