### ISSUE TITLE
Search Page Cleanup

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/mit-open#640]
### Description/Context
Minor tweaks for the search page:

- [x] Remove the "active facets" display, but keep the "Filters" label and "Clear All" button. "Clear all" should only be visible when facets are active. 
    - *Rationale for removal:* It shows redundant information. Additionally, it causes layout shift when facets get added/removed
- [x] Remove horizontal padding on tabpanels
- [x] Add "Offered by" filter
- [x] Use the same URL query parameters as the search API.
- [x] URL query parameters should work even if the corresponding facet isn't in the UI.
    - This makes demoing potential changes to the app easier, is simple, and doesn't have any real downsides. Additionally, it could be useful for creating "search lists" to be used with channels. 

### Plan/Design
URL parameter changes will be handled in course-search-utils.

**Comment by steven-hatch** [comment]
I would expect A - Clear all resets sidebar filters. 

I am saying this because the "clear all" is in close proximity to filters, and not visually near the tabs. If these were somehow visually connected then clear all would be expected to reset the page. 

This is not related to your work yet, but if user expects to be reset to original search when selecting "clear all" and starts filtering again they my not realize they are still on podcasts tab. The content in the cards, maybe the styling of the card, and empty states need to remind user that they still have 'podcasts' selected (in addition to the tab being selected). Thanks!
